apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app

spec:
  type: NodePort
  selector:
    app: todo-label
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30003
